parameters:
    braunedigital.pitcher.client.class: BrauneDigital\PitcherBundle\Client\Client
    braunedigital.pitcher.exception_listener.class: BrauneDigital\PitcherBundle\EventSubscriber\ExceptionSubscriber

services:
    pitcher.client:
        class:  "%braunedigital.pitcher.client.class%"
        arguments: ["@service_container"]
        calls:
            - [setLogger, ['@monolog.logger.pitcher']]

    pitcher.exception_listener:
        class: "%braunedigital.pitcher.exception_listener.class%"
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setClient, ['@pitcher.client']]
            - [setContainer, ['@service_container']]